export const dashboardStats = {
  projectCount: 1981,
  originalCost: 3712662.01,
  revisedCost: 4278402.39,
  expenditure: 2036107.49,
};
export const projects = [
  {
    id: "P-001",
    sector: "Education",
    organization: "INDIAN INSTITUTE OF TECHNOLOGY PALAKKAD",
    name: "Phase B of Construction of Permanent Campus of IIT Palakkad",
    originalCost: 1527,
    revisedCost: 1527,
    progress: 0,
    completionDate: "31/10/2028",
    risk: 71,
    costRisk: 42,
    timeRisk: 76,
    status: "High",
    warnings: 3,
    factors: [
      ["Physical progress", 32],
      ["Schedule variance", 27],
      ["Cost trend", 18],
      ["Historical delay", 13],
    ],
    recommendations: [
      "Review construction milestone dependencies",
      "Increase monitoring frequency",
      "Validate upcoming completion milestones",
    ],
  },

  {
    id: "P-002",
    sector: "Waste & Water",
    organization: "National Mission for Clean Ganga",
    name: "Interception & Diversion with Rehabilitation of sewerage scheme at Agra",
    originalCost: 842,
    revisedCost: 842,
    progress: 80,
    completionDate: "31/12/2026",
    risk: 36,
    costRisk: 24,
    timeRisk: 39,
    status: "Medium",
    warnings: 1,
    factors: [
      ["Physical progress", 34],
      ["Completion proximity", 26],
      ["Cost stability", 14],
    ],
    recommendations: [
      "Continue milestone tracking",
      "Monitor final implementation phase",
    ],
  },

  {
    id: "P-003",
    sector: "Logistics Infrastructure",
    organization:
      "National Highways & Infrastructure Development Corporation Ltd.",
    name: "Integrated Multi Modal Logistics Hub at Nangal Chaudhary",
    originalCost: 763,
    revisedCost: 763,
    progress: 60,
    completionDate: "15/05/2028",
    risk: 58,
    costRisk: 49,
    timeRisk: 63,
    status: "High",
    warnings: 2,
    factors: [
      ["Physical progress", 29],
      ["Schedule variance", 25],
      ["Resource utilization", 21],
      ["Cost movement", 16],
    ],
    recommendations: [
      "Review resource allocation",
      "Track construction milestones",
      "Evaluate schedule recovery options",
    ],
  },

  {
    id: "P-004",
    sector: "Railways",
    organization: "National High Speed Rail Corporation",
    name: "Mumbai-Ahmedabad High Speed Rail Project - 508 km",
    originalCost: 108000,
    revisedCost: 108000,
    progress: 60,
    completionDate: "31/12/2029",
    risk: 47,
    costRisk: 31,
    timeRisk: 55,
    status: "Medium",
    warnings: 2,
    factors: [
      ["Physical progress", 30],
      ["Schedule variance", 24],
      ["Resource utilization", 18],
      ["Cost stability", 11],
    ],
    recommendations: [
      "Continue milestone monitoring",
      "Review high-impact construction dependencies",
    ],
  },

  {
    id: "P-005",
    sector: "Urban Public Transport",
    organization: "Chennai Metro Rail Limited",
    name: "Chennai Metro Rail Phase-II Development Project",
    originalCost: 63246,
    revisedCost: 63246,
    progress: 53,
    completionDate: "31/08/2029",
    risk: 64,
    costRisk: 57,
    timeRisk: 69,
    status: "High",
    warnings: 4,
    factors: [
      ["Schedule variance", 31],
      ["Physical progress", 25],
      ["Cost movement", 22],
      ["Resource utilization", 14],
    ],
    recommendations: [
      "Conduct detailed schedule review",
      "Identify critical-path activities",
      "Review cost escalation drivers",
    ],
  },

  {
    id: "P-006",
    sector: "Telecommunication",
    organization: "Department of Telecommunications",
    name: "BharatNet",
    originalCost: 61109,
    revisedCost: 188000,
    progress: 82,
    completionDate: "31/03/2027",
    risk: 82,
    costRisk: 91,
    timeRisk: 48,
    status: "Critical",
    warnings: 5,
    factors: [
      ["Cost escalation", 41],
      ["Revised project cost", 25],
      ["Schedule variance", 14],
      ["Physical progress", 10],
    ],
    recommendations: [
      "Investigate major cost escalation",
      "Review revised project scope",
      "Conduct financial risk assessment",
    ],
  },

  {
    id: "P-007",
    sector: "Energy Storage",
    organization: "Ministry of Petroleum & Natural Gas",
    name: "Rajasthan Refinery Project",
    originalCost: 43129,
    revisedCost: 79459,
    progress: 92,
    completionDate: "30/06/2026",
    risk: 76,
    costRisk: 89,
    timeRisk: 37,
    status: "High",
    warnings: 4,
    factors: [
      ["Cost escalation", 43],
      ["Revised cost", 27],
      ["Completion proximity", 17],
      ["Physical progress", 8],
    ],
    recommendations: [
      "Review final-stage expenditure",
      "Validate remaining project scope",
      "Monitor completion milestones closely",
    ],
  },

  {
    id: "P-008",
    sector: "Metals & Mining",
    organization: "National Aluminium Company Limited",
    name: "Expansion of Alumina Refinery Plant",
    originalCost: 4103,
    revisedCost: 5677,
    progress: 94,
    completionDate: "30/06/2026",
    risk: 69,
    costRisk: 73,
    timeRisk: 41,
    status: "High",
    warnings: 3,
    factors: [
      ["Cost escalation", 37],
      ["Completion proximity", 24],
      ["Physical progress", 18],
    ],
    recommendations: [
      "Review remaining expenditure",
      "Monitor commissioning activities",
    ],
  },
];

export const alerts = [
  {
    id: 1,
    severity: "Critical",
    project: "BharatNet",
    message: "Latest revised cost significantly exceeds original cost.",
    type: "Cost escalation",
  },
  {
    id: 2,
    severity: "High",
    project: "Rajasthan Refinery Project",
    message: "Large cost revision detected.",
    type: "Financial risk",
  },
  {
    id: 3,
    severity: "High",
    project: "Chennai Metro Rail Phase-II",
    message: "Schedule and physical progress require attention.",
    type: "Schedule risk",
  },
  {
    id: 4,
    severity: "Medium",
    project: "IIT Palakkad",
    message: "Physical progress remains at an early stage.",
    type: "Progress signal",
  },
];

export const reports = [
  {
    month: "March 2026",
    type: "Project Monitoring",
    title: "Monthly Flash Report",
  },
  {
    month: "January 2026",
    type: "Performance Monitoring",
    title: "Monthly Review Report",
  },
  {
    month: "February 2026",
    type: "Project Monitoring",
    title: "Monthly Flash Report",
  },
  {
    month: "January 2026",
    type: "Project Monitoring",
    title: "Monthly Flash Report",
  },
];
