"""
Router for the Knowledge-Graph endpoints: JSON graph, JSON report and rendered HTML report.
"""

from typing import Optional

from fastapi import APIRouter, Depends, Query
from fastapi.responses import HTMLResponse
from sqlalchemy.orm import Session

from ..database import get_db
from ..knowledge_graph import build_graph, build_report

router = APIRouter(prefix="/graph", tags=["Knowledge Graph"])


@router.get("")
def get_knowledge_graph(
    db: Session = Depends(get_db),
    project_id: Optional[str] = Query(None, description="Restrict to one project"),
    ministry: Optional[str] = Query(None, description="Filter by ministry name/substring"),
    limit: int = Query(150, ge=1, le=500),
):
    """GET /graph — knowledge graph of projects, ministries, agencies, sectors and SHAP risks."""
    return build_graph(db, project_id=project_id, ministry=ministry, limit=limit)


@router.get("/report")
def get_graph_report(
    db: Session = Depends(get_db),
    project_id: Optional[str] = Query(None),
    ministry: Optional[str] = Query(None),
    limit: int = Query(100, ge=1, le=500),
):
    """GET /graph/report — narrative, relationship-aware report as structured JSON."""
    return build_report(db, project_id=project_id, ministry=ministry, limit=limit)


@router.get("/report.html", response_class=HTMLResponse)
def get_graph_report_html(
    db: Session = Depends(get_db),
    project_id: Optional[str] = Query(None),
    ministry: Optional[str] = Query(None),
    limit: int = Query(100, ge=1, le=500),
):
    """GET /graph/report.html — rendered HTML wrapper around the narrative report."""
    report = build_report(db, project_id=project_id, ministry=ministry, limit=limit)
    article = "".join(
        f"<h2>{sec['heading']}</h2>\n<div class='body'>{sec['body']}</div>\n"
        for sec in report["sections"]
    )
    html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{report['title']}</title>
<style>
  body {{ font-family: system-ui, sans-serif; max-width: 820px; margin: 40px auto; padding: 0 20px; color: #0f172a; }}
  h1 {{ color: #4f46e5; border-bottom: 2px solid #e0e7ff; padding-bottom: 10px; }}
  h2 {{ color: #1e293b; margin-top: 28px; }}
  .body {{ background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 10px; padding: 14px 18px; line-height: 1.65; white-space: pre-wrap; }}
  .body:empty {{ display: none; }}
  .muted {{ color: #64748b; font-size: 0.85em; }}
</style>
</head>
<body>
<h1>{report['title']}</h1>
<p class="muted">Generated by Dhrishti Knowledge-Graph reporting. Projects covered: {report['generated_for']['projects']}.</p>
{article}
</body>
</html>"""
    return html